python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/0 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/1 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/2 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/3 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/4 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/5 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/6 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/7 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/8 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/9 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/10 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/11 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/12 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/13 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/14 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/15 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/16 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/17 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/18 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/19 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/20 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/21 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/22 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/23 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/24 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/25 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/26 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/27 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/28 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/29 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/30 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/31 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/32 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/33 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/34 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/35 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/36 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/37 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/38 &
python tr1.py /Users/karthikeyan/Desktop/Names\ Data/Translate/MultiFiles/39 &
